### ISSUE TITLE
NoMethodError when removed_member_ids is nil

### ISSUE THREAD

**Issue by holdank** [shardlab/discordrb#186]
# Summary
seeing this error result in closed connections

```
[ERROR` : websocket @ 2022-10-16 15:22:46.660] Exception: #<NoMethodError: undefined method `each' for nil:NilClass

        data['removed_member_ids'].each do |member_id|
                                  ^^^^^>
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/bot.rb:1603:in `handle_dispatch'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/bot.rb:769:in `dispatch'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:730:in `handle_dispatch'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:694:in `handle_message'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:631:in `websocket_loop'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:579:in `connect'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:473:in `block in connect_loop'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:472:in `loop'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:472:in `connect_loop'
[ERROR : websocket @ 2022-10-16 15:22:46.661] /usr/local/rvm/gems/ruby-3.1.2/bundler/gems/discordrb-1cd5603d23e0/lib/discordrb/gateway.rb:168:in `block in run_async'
[ERROR : websocket @ 2022-10-16 15:25:34.644] The websocket connection has closed: (no information)
[INFO : websocket @ 2022-10-16 15:25:34.644] Instant reconnection flag was set - reconnecting right away
[INFO : websocket @ 2022-10-16 15:25:34.984] Resumed
```

looks like `added_members` and `removed_member_ids` falls back to empty array [here](https://github.com/shardlab/discordrb/blob/77080de8c11a0e102833c24a90afbb532557aff4/lib/discordrb/events/threads.rb#L79-L82) in thread.rb, but [this code](https://github.com/shardlab/discordrb/blob/ac58cf5853c5c5b4948e9a26ab305a203fac5651/lib/discordrb/bot.rb#L1598-L1605) in bot.rb is still accessing the data hash directly which can result in these being nil and causing the error. 

The closed connection happens a few minutes later - I was assuming it was related, but it may not be.

---

## Environment

ubuntu 20.0.4

**Ruby version:**

3.1.2

**Discordrb version:**

specs:
    discordrb (3.4.2)
      discordrb-webhooks (~> 3.4.2)
      ffi (>= 1.9.24)
      opus-ruby
      rest-client (>= 2.0.0)
      websocket-client-simple (>= 0.3.0)
    discordrb-webhooks (3.4.2)
      rest-client (>= 2.0.0)

**Comment by Daniel-Worrall** [comment]
Introduced in #141, these [fields](https://discord.com/developers/docs/topics/gateway-events#thread-members-update-thread-members-update-event-fields) are [optional](https://discord.com/developers/docs/reference#nullable-and-optional-resource-fields-example-nullable-and-optional-fields).

Will send a PR

**Comment by holdank** [comment]
Ah i see i had the flow backwards.

**Comment by Droid00000** [comment]
Fixed in 3.5! Ty for the patches all
