### ISSUE TITLE
Attempting to create a select menu or button component in a slash command interaction response fails with Invalid Form Body.

### ISSUE THREAD

**Issue by SirTony** [shardlab/discordrb#258]
# Summary

When attempting to respond to a slash command with a button, select menu, or other component beside an embed, the REST call fails with an invalid form body error.

```
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] Invalid Form Body
        - data.components[0].components[0].emoji.name: Invalid emoji
        - data.components[1].components[0].options[0].emoji.name: Invalid emoji
        - data.components[1].components[0].options[1].emoji.name: Invalid emoji
        - data.components[1].components[0].options[2].emoji.name: Invalid emoji
        - data.components[1].components[0].options[3].emoji.name: Invalid emoji
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] Exception: #<Discordrb::Errors::InvalidFormBody: Discordrb::Errors::InvalidFormBody>
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/.local/share/gem/ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/api.rb:124:in `rescue in request'
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/.local/share/gem/ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/api.rb:113:in `request'
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/.local/share/gem/ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/api/interaction.rb:13:in `create_interaction_response'
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/.local/share/gem/ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/data/interaction.rb:108:in `respond'
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/.local/share/gem/ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/events/interactions.rb:39:in `respond'
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/RubymineProjects/Landlady/src/discord/bot.rb:48:in `block in initialize'
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/.local/share/gem/ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/events/interactions.rb:289:in `call'
[ERROR : it-1243359675232026664 @ 2024-05-23 20:27:27.273] /home/tony/.local/share/gem/ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/bot.rb:1561:in `block in handle_dispatch'

```

This appears to be because the `:emoji` key on the component hash is set to an empty hash instead of `nil` when there are no emojis present, as seen when inspecting the `components` parameter of

https://github.com/shardlab/discordrb/blob/edad88dc5d2fcb79985a8bf9d7da24702a544783/lib/discordrb/api/interaction.rb#L9

Using `pp` to look at the output of the select menu and button response from the slash commands example, the following is printed:

```
[{:type=>1, :components=>[{:type=>2, :label=>"Test!", :emoji=>{}, :style=>1, :custom_id=>"test_button:1", :disabled=>nil, :url=>nil}]},
 {:type=>1,
  :components=>
   [{:type=>3,
     :options=>
      [{:label=>"Foo", :value=>"foo", :description=>nil, :emoji=>{}, :default=>nil},
       {:label=>"Bar", :value=>"bar", :description=>nil, :emoji=>{}, :default=>nil},
       {:label=>"Baz", :value=>"baz", :description=>nil, :emoji=>{}, :default=>nil},
       {:label=>"Bazinga", :value=>"bazinga", :description=>nil, :emoji=>{}, :default=>nil}],
     :placeholder=>"Select me!",
     :min_values=>nil,
     :max_values=>3,
     :custom_id=>"test_select",
     :disabled=>nil}]}]

```

https://github.com/shardlab/discordrb/blob/edad88dc5d2fcb79985a8bf9d7da24702a544783/examples/slash_commands.rb#L71

A quick hack to hardpatch `create_interaction_response` to set the `:emoji` key to `nil` causes the example to work as expected.

```
    data[:components][0][:components][0][:emoji] = nil
    data[:components][1][:components][0][:options][0][:emoji] = nil
    data[:components][1][:components][0][:options][1][:emoji] = nil
    data[:components][1][:components][0][:options][2][:emoji] = nil
    data[:components][1][:components][0][:options][3][:emoji] = nil
```

---

## Environment

**Ruby version:** ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]

**Discordrb version:**

```
*** LOCAL GEMS ***

discordrb (3.5.0)
discordrb-webhooks (3.5.0)
```

**Comment by SirTony** [comment]
Upon closer inspection, this appears to be a bug in the webhook builder

the code

```ruby
      emoji = case emoji
              when Integer, String
                emoji.to_i.positive? ? { id: emoji } : { name: emoji }
              else
                emoji.to_h
              end
```

in the `View` builder for the various components is responsible.

Particularly the line

```ruby
emoji.to_h
```

as `nil.to_h` produces an empty hash when it should stay `nil` so the API doesn't complain.

https://github.com/shardlab/discordrb/blob/edad88dc5d2fcb79985a8bf9d7da24702a544783/lib/discordrb/webhooks/view.rb#L48-L53
