### ISSUE TITLE
Problems with TLS/SSL

### ISSUE THREAD

**Issue by suzukiception** [shardlab/discordrb#266]
When i try to run the bot, this error appears:
[ERROR : websocket @ 2024-06-28 14:23:08.236] An error occurred while connecting to the websocket!
[ERROR : websocket @ 2024-06-28 14:23:08.236] Exception: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=162.159.133.234:443 state=error: tlsv1 unrecognized name>
[ERROR : websocket @ 2024-06-28 14:23:08.236] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:519:in `connect'
[ERROR : websocket @ 2024-06-28 14:23:08.236] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:519:in `obtain_socket'
[ERROR : websocket @ 2024-06-28 14:23:08.236] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:569:in `connect'
[ERROR : websocket @ 2024-06-28 14:23:08.236] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:473:in `block in connect_loop'
[ERROR : websocket @ 2024-06-28 14:23:08.236] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:472:in `loop'
[ERROR : websocket @ 2024-06-28 14:23:08.236] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:472:in `connect_loop'
[ERROR : websocket @ 2024-06-28 14:23:08.236] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:168:in `block in run_async'
[ERROR : websocket @ 2024-06-28 14:23:09.308] An error occurred while connecting to the websocket!
[ERROR : websocket @ 2024-06-28 14:23:09.308] Exception: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=162.159.136.234:443 state=error: tlsv1 unrecognized name>
[ERROR : websocket @ 2024-06-28 14:23:09.308] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:519:in `connect'
[ERROR : websocket @ 2024-06-28 14:23:09.308] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:519:in `obtain_socket'
[ERROR : websocket @ 2024-06-28 14:23:09.308] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:569:in `connect'
[ERROR : websocket @ 2024-06-28 14:23:09.308] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:473:in `block in connect_loop'
[ERROR : websocket @ 2024-06-28 14:23:09.308] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:472:in `loop'
[ERROR : websocket @ 2024-06-28 14:23:09.308] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:472:in `connect_loop'
[ERROR : websocket @ 2024-06-28 14:23:09.308] /home/runner/ParallelMountainousHypertalk/.bundle/ruby/3.2.0/gems/discordrb-3.5.0/lib/discordrb/gateway.rb:168:in `block in run_async'

How can i fix this? (I am using Replit, btw)

**Comment by swarley** [comment]
Replit is generally discouraged as much of their IP range is blocked by discord

**Comment by suzukiception** [comment]
> Replit is generally discouraged as much of their IP range is blocked by discord



> Replit is generally discouraged as much of their IP range is blocked by discord

Well, gonna have to migratethe project somewhere. Thanks for the reply!

**Comment by Droid00000** [comment]
As Swarley said, this is a downside of using Replit. Nonetheless, thank you for the report!
