### ISSUE TITLE
On any run of 3.40+: Gateway message error! Exception: #<ArgumentError: wrong number of arguments (given 2, expected 3)>

### ISSUE THREAD

**Issue by joshjordan** [shardlab/discordrb#56]
# Summary

I feel like I must be doing something wrong, but it seems like any version of discordrb 3.4.0+ fails to run for me, even in the very basic hello world use case:

```
bot = Discordrb::Bot.new(token: 'xxx')
bot.run
```

Results in:

```
[ERROR : websocket @ 2021-05-23 19:37:06.054] Gateway message error!
[ERROR : websocket @ 2021-05-23 19:37:06.054] Exception: #<ArgumentError: wrong number of arguments (given 2, expected 3)>
[ERROR : websocket @ 2021-05-23 19:37:06.054] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/data/member.rb:59:in `initialize'
[ERROR : websocket @ 2021-05-23 19:37:06.054] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/data/message.rb:107:in `new'
[ERROR : websocket @ 2021-05-23 19:37:06.054] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/data/message.rb:107:in `initialize'
[ERROR : websocket @ 2021-05-23 19:37:06.055] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/bot.rb:1112:in `new'
[ERROR : websocket @ 2021-05-23 19:37:06.055] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/bot.rb:1112:in `handle_dispatch'
[ERROR : websocket @ 2021-05-23 19:37:06.055] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/bot.rb:709:in `dispatch'
[ERROR : websocket @ 2021-05-23 19:37:06.055] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:727:in `handle_dispatch'
[ERROR : websocket @ 2021-05-23 19:37:06.055] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:691:in `handle_message'
[ERROR : websocket @ 2021-05-23 19:37:06.055] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:628:in `websocket_loop'
[ERROR : websocket @ 2021-05-23 19:37:06.055] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:576:in `connect'
[ERROR : websocket @ 2021-05-23 19:37:06.056] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:470:in `block in connect_loop'
[ERROR : websocket @ 2021-05-23 19:37:06.056] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:469:in `loop'
[ERROR : websocket @ 2021-05-23 19:37:06.056] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:469:in `connect_loop'
[ERROR : websocket @ 2021-05-23 19:37:06.056] /Users/jjordan/.rvm/gems/ruby-2.6.2/bundler/gems/discordrb-c5f5ea8c03e8/lib/discordrb/gateway.rb:165:in `block in run_async'
```

This appears to be due to this commit: https://github.com/shardlab/discordrb/commit/751261ca3d39b0cea84ff771e8380ca9a54f736c which calls `Member.new` with 2 arguments, but the `Member#initialize` method has taken 3 arguments for the past 3 years. Surely I'm not the only person who has run this server for the past few months, but I don't see another issue for this. So, I wonder what's unique about my usage -- it seems that this code path would always cause this error.

---

## Environment

Mac OS, Ruby 2.6.2, discordrb 3.40 or 3.4.1 or 3.4.2

**Comment by swarley** [comment]
Thank you for the report. I'm not sure how this flew under the radar so long.

**Comment by joshjordan** [comment]
Pretty amazing turnaround. Thanks!
